spring:
  # 配置数据源信息
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 配置连接数据库的各个信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:mysql://192.168.1.70:3306/mybatis_plus?characterEncoding=utf-8&userSSL=false
    #    url: jdbc:mysql://192.168.12.201:3306/mybatis_plus?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    #    url: mpw:OMIdDikrwSDuvMSKRYvySroTsQe6N/BAWhGYEL8YlVYk88JGdQM2kJClwKeKh1sbfydXH6ce9/QBFfi5PXMynS2hSFNLpcwKOrVzNUQbqPN2c7ggb9sdLf3/YwRQiesOymVUizJJ9W7N9IHXiwsUMWSkobMZpXoBdGP9eU48b1E=
    #    username: mpw:IF15DE4tKkaVOpgDOh0Ghw==
    #    password: mpw:ki5F2b7SnyKNhsywUjzmtw==
    username: root
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  # 设置MyBatis-Plus的全局配置
  global-config:
    db-config:
      # 设置实体类所对应的表的统一前缀
      #      table-prefix: t_
      table-prefix: a_
      # 设置统一的主键生成策略
  #      id-type: auto

  # 配置类型别名所对应的包
  type-aliases-package: com.joing.mybatisplus.entity
  # 扫描通用枚举的包
  type-enums-package: com.joing.mybatisplus.enums